#include <stdio.h>
#include <math.h>

/*
** Each new term in the Fibonacci sequence is generated by adding the previous two terms.
** By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
** By considering the terms in the Fibonacci sequence whose values do not exceed four million,
** find the sum of the even-valued terms.
*/

#define PHI_3POW 4.236068

int		main(void)
{
	long sum = 0;
	for (int a = 1, b = 2; a < 4000000; b += a, a = b - a)
	{
		if (a % 2 == 0)
			sum += a;
	}

//	using PHI golden ratio
//	long sum = 0;
//	for (double i = 2; i < 4000000; i = round(i * PHI_3POW))
//		sum += i;
	printf("%ld\n", sum);
	return 0;
}
